<?php
/**
 * Created by PhpStorm.
 * User: hofer
 * Date: 24.10.2017
 * Time: 22:23
 */


/**
 * Implements hook_node_view().
 */
function meetup_node_view($node, $view_mode, $langcode) {
	$content_type = $node->type;
	if(!strcmp($content_type, "event")) {
		$node->content['meetup_button_teilnehmen'] = array(
			'#prefix' => "<div id='meetup-button-teilnehmen'>",
			'#suffix' => "</div>",
			'#markup' => meetup_button_teilnehmen(),
			'#weight' => 1000,
		);
		$node->content['meetup_button_interesse'] = array(
			'#prefix' => "<div id='meetup-button-interesse'>",
			'#suffix' => "</div>",
			'#markup' => meetup_button_interesse(),
			'#weight' => 2000,
		);
	}
}

/**
 * Implements hook_menu().
 */
function meetup_menu() {
	$items['meetup/teilnehmen/%'] = array(
		'title' => '',
		'description' => 'Different visualization.',
		'page callback' => 'meetup_teilnehmen',
		'access callback' => TRUE,
		'page arguments' => array(1),
	);

	$items['meetup/interesse/%'] = array(
		'title' => '',
		'description' => 'Different visualization.',
		'page callback' => 'meetup_interesse',
		'access callback' => TRUE,
		'page arguments' => array(2),
	);



	return $items;
}

function meetup_button_teilnehmen(){
	$node = menu_get_object();
	return "<a href='" . base_path() . "meetup/teilnehmen/" . $node->nid . "'>Ich nehme teil</a>";
}

function meetup_button_interesse(){
	$node = menu_get_object();
	return "<a href='" . base_path() . "meetup/interesse/" . $node->nid . "'>Ich bin interessiert</a>";
}

function meetup_teilnehmen($node_id){
	$message = "<p>Vielen Dank für Ihre Teilnahme am Event.</p>";
	return $message;
}

function meetup_interesse($node_id) {
	$message = "<p>Vielen Dank für Ihr Interesse am Event.</p><p><a href=\"#\" class=\"back\">Back</a></p>";


	return $message;
}


